name: Install Basilisk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  local:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      HOME : ${{ github.workspace }}
      LOCAL_INSTALL : yes

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install Mako
      
      - name: update and upgrade
        run: |
          sudo apt update
          sudo apt upgrade
          touch $HOME/.bashrc     # needed later

      - name: get installer script
        run: wget https://raw.githubusercontent.com/highwave-project/ICHEC_help/main/install_basilisk.sh

      - name: modify permissions
        run: chmod a+x install_basilisk.sh
  
      - name: run install script
        run: ./install_basilisk.sh

      - name: testing
        env: 
          TESTING : yes
          BASILISK: ${{ github.workspace }}/basilisk/src
        run: ./install_basilisk.sh

  graphics:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      HOME : ${{ github.workspace }}
      BUILD_GRAPHICS : yes
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install Mako

      - name: install deps
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install gfortran xcb valgrind graphviz valgrind gifsicle pstoedit libxcb-shape0-dev libxcb-xfixes0-dev libx11-xcb-dev libxcb-dri2-0-dev libdrm-dev
          touch $HOME/.bashrc     # needed later
        
      - name: get installer script
        run: wget https://raw.githubusercontent.com/highwave-project/ICHEC_help/main/install_basilisk.sh

      - name: modify permissions
        run: chmod a+x install_basilisk.sh
  
      - name: run install script
        run: ./install_basilisk.sh

      - name: testing
        env:
          TESTING : yes
          BASILISK: ${{ github.workspace }}/basilisk/src
        run: ./install_basilisk.sh
