name: Install Basilisk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  local:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: run install script
        run: |
          wget https://raw.githubusercontent.com/highwave-project/ICHEC_help/main/install_basilisk.sh
          chmod a+x install_basilisk.sh
          export LOCAL_INSTALL=yes
          ./install_basilisk.sh

  graphics:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: install mesa dep
        run: sudo apt install xcb  
  
      - name: run install script
        run: |
          wget https://raw.githubusercontent.com/highwave-project/ICHEC_help/main/install_basilisk.sh
          chmod a+x install_basilisk.sh
          export BUILD_GRAPHICS=yes
          ./install_basilisk.sh
